In [2]:
import numpy as np

In [4]:
#create a new ndarray from scatch
my_array = np.array([1.1, 9.2, 8.1, 4.7])

In [5]:
#show rows and columns
my_array.shape

(4,)

In [6]:
#show dimension of an array
my_array.ndim

1

In [7]:
my_array.shape[0]

4

In [8]:
my_array.shape[1]

IndexError: tuple index out of range

In [9]:
array_2d = np.array([[1, 2, 3, 9],
                     [5, 6, 7, 8]])

In [10]:
print(f"array_2d has {array_2d.ndim} dimensions")
print(f"Its shape is {array_2d.shape}")
print(f"Its has {array_2d.shape[0]} rows and {array_2d.shape[1]} columns")
print(array_2d)

array_2d has 2 dimensions
Its shape is (2, 4)
Its has 2 rows and 4 columns
[[1 2 3 9]
 [5 6 7 8]]


In [11]:
#access all the values in the first row
array_2d[0, :]

array([1, 2, 3, 9])

In [16]:
mystery_array = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                           
                          [[7, 86, 6, 98],
                           [5, 1, 0, 4]],

                           [[5, 36, 32, 48],
                            [97, 0, 27, 18]]])

In [17]:
print(f"Wir have {mystery_array.ndim} dimensions")
print(f"The shape is {mystery_array.shape}")

Wir have 3 dimensions
The shape is (3, 2, 4)


In [18]:
mystery_array[2, 1, 3]


18

In [20]:
#All the first elements on the axis number 3
mystery_array[:, :, 0]

array([[ 0,  4],
       [ 7,  5],
       [ 5, 97]])

In [24]:
liste = []
for i in range(1, 10):
    liste.append(i)

print(liste)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [26]:
dir(list)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [29]:
A = eval("2+4")
type(A)

int

In [30]:
B = eval("2")
type(B)

int

# Methode : arange(start, stop, step, <b>dtype= int</b>)

## . nbre d element dans le vecteur = (stop -star)/step
## . la valeur limite du vecteur = stop*start
## . le nouveau step = int(start + step) - int(start)

In [32]:
np.arange(0, 5, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [4]:
np.arange(-3, 3, 0.5)

array([-3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ,
        2.5])

In [6]:
np.arange(-3, 3, 0.5, dtype=int)

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [25]:
np.arange(2, 5, 0.8, dtype=int)# nouveau pas = int(0+0.5) - int(0)= 0

array([2, 2, 2, 2])

# Challenge 1:
    Use .arange()to createa a vector a with values ranging from 10 to 29. 
   

In [29]:
a = np.arange(10, 30, 1)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

# Challenge 2:

    Use Python slicing techniques on a to:

        + Create an array containing only the last 3 values of a

        + Create a subset with only the 4th, 5th, and 6th values

        + Create a subset of a containing all the values except for 
         the first 12 (i.e., [22, 23, 24, 25, 26, 27, 28, 29])

        + Create a subset that only contains the even numbers (i.e, every second number)

In [30]:
the_3_last_values = a[-3:]
the_3_last_values

array([27, 28, 29])

In [38]:
a[:1] # j accede ici a la premier ligne , premiere colonne
      # resultat es un array

array([10])

In [39]:
a[0] # ici j accede a la valeur de la premiere ligne 

10

In [40]:
a[3:6]

array([13, 14, 15])

In [41]:
a[:-3]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26])